---
- name: "This playbook install httpd or apache2 and can be called via tags"
  hosts: all
  become: true
  tasks:
  - name: "install httpd packages"
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
    tags: install_apache2

  - name: "start httpd service"
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    tags: start_apache2
    ignore_errors: yes

  - name: "install apache2 packages"
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: install_apache2

  - name: "start apache2 service"
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    tags: start_apache2
