---
- name: "This playbook installs packages"
  hosts: all
  become: true
  tasks:
  - name: "install packages via lists"
    yum:
      name:
       - git
       - make
       - gcc
       - wget
       - telnet
       - gzip
      state: installed
    when: ansible_os_family == "RedHat"


