---
- name: "This playbook installs apache2 and starts the service"
  hosts: debtar1
  become: true
  tasks:
  - name: "Install apache2 on ubuntu system"
    apt:
     name: apache2
     state: present

  - name: "Starting apache2 service"
    service:
      name: apache2
      state: started
